name:                Funkadelic
version:             0.1.0.0
github:              "githubuser/Funkadelic"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Funkadelic#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >=3.1
- containers >= 0.4.0.0
- mtl >= 2.2.2
- transformers >= 0.5.5.0

library:
  source-dirs: src

executables:
  Funkadelic-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Funkadelic

tests:
  Funkadelic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Funkadelic
    - hspec >= 2.6.0
    - template-haskell >= 2.11.0.0
    - hspec-expectations-match >= 0.2.0.0
